services:
  app:
    image: meu-node:v2  # → Já Existente
    # build: .  → Cria um novo
    ports: 
      - 4000:3000
  db: 
    image: mongo
    volumes:
      - mongo-data:/data/db

volumes: 
  mongo-data:
  

